### ISSUE TITLE
Plugin fails to compile with new quartz 1.0RC2

### ISSUE THREAD

**Issue by calvinthomas** [jamescookie/quartz-monitor#9]
Quartz 1.0RC is required to use grails 2 and above however when trying to compile application after installing Quartz 1.0RC2 and Quartz-monitor 0.2 the following error occurs.

| Error Compilation error: startup failed:
Compile error during compilation with javac.
C:\Users\cthomas.grails\2.0.3\projects\process\plugins\quartz-monitor-0.2\src\java\org\grails\plugins\quartz\QuartzMonitorJobFactory.java:3: package org.codehaus.groovy.grails.plugins.quartz does not exist
import org.codehaus.groovy.grails.plugins.quartz.GrailsJobFactory;
                                                ^
C:\Users\cthomas.grails\2.0.3\projects\process\plugins\quartz-monitor-0.2\src\java\org\grails\plugins\quartz\QuartzMonitorJobFactory.java:20: cannot find symbol
symbol: class GrailsJobFactory
public class QuartzMonitorJobFactory extends GrailsJobFactory {
                                             ^
C:\Users\cthomas.grails\2.0.3\projects\process\plugins\quartz-monitor-0.2\src\java\org\grails\plugins\quartz\QuartzMonitorJobFactory.java:49: cannot find symbol
symbol  : class GrailsTaskClassJob
location: class org.grails.plugins.quartz.QuartzMonitorJobFactory.QuartzDisplayJob
        GrailsTaskClassJob job;
        ^
C:\Users\cthomas.grails\2.0.3\projects\process\plugins\quartz-monitor-0.2\src\java\org\grails\plugins\quartz\QuartzMonitorJobFactory.java:53: cannot find symbol
symbol  : class GrailsTaskClassJob
location: class org.grails.plugins.quartz.QuartzMonitorJobFactory.QuartzDisplayJob
        public QuartzDisplayJob(GrailsTaskClassJob job, Map<String, Object> jobDetails, SessionFactory sessionFactory) {
                                ^
C:\Users\cthomas.grails\2.0.3\projects\process\plugins\quartz-monitor-0.2\src\java\org\grails\plugins\quartz\QuartzMonitorJobFactory.java:31: cannot find symbol
symbol  : variable super
location: class org.grails.plugins.quartz.QuartzMonitorJobFactory
        Object job = super.createJobInstance(bundle);
                     ^
C:\Users\cthomas.grails\2.0.3\projects\process\plugins\quartz-monitor-0.2\src\java\org\grails\plugins\quartz\QuartzMonitorJobFactory.java:32: cannot find symbol
symbol  : class GrailsTaskClassJob
location: class org.grails.plugins.quartz.QuartzMonitorJobFactory
        if (job instanceof GrailsTaskClassJob) {
                           ^
C:\Users\cthomas.grails\2.0.3\projects\process\plugins\quartz-monitor-0.2\src\java\org\grails\plugins\quartz\QuartzMonitorJobFactory.java:40: cannot find symbol
symbol  : class GrailsTaskClassJob
location: class org.grails.plugins.quartz.QuartzMonitorJobFactory
            job = new QuartzDisplayJob((GrailsTaskClassJob) job, map, sessionFactory);
                                        ^
7 errors
1 error
